### ISSUE TITLE
schemeless URLs and discoverAuthorizationEndpoint()

### ISSUE THREAD

**Issue by jonnybarnes** [indieweb/indieauth-client-php#1]
The method `discoverAuthorizationEndpoint()` fails when passed a schemeless URL such as `aaronparecki.com`.

**Comment by aaronpk** [comment]
I'm not sure it's safe to assume a scheme if none is present. Technically everything should be https, but it seems weird to automatically add that if no scheme is present.

**Comment by jonnybarnes** [comment]
It would strike me as most sensible to pass `http://` as the scheme, then follow a redirect to `https://` if the server sends one.

One may even consider monitoring for [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) headers, but that would require some kind of cache/storage of which sites have sent such a header.
