### ISSUE TITLE
Myabe use random_compat?

### ISSUE THREAD

**Issue by jonnybarnes** [indieweb/indieauth-client-php#14]
https://github.com/paragonie/random_compat provides the `random_bytes` function in PHP 5.x

You could add it as an suggested dependency so people could add it themselves if they are still on PHP 5.x, then just throw an exception if random_bytes isn’t defined

**Comment by aaronpk** [comment]
I'd rather not introduce another dependency for this, plus you can always just generate the state parameter yourself using a library like `random_compat` if you don't want to use the helper function defined in this library.
