### ISSUE TITLE
_discoverEndpoint skips empty HREFs, should resolve them.

### ISSUE THREAD

**Issue by Zegnat** [indieweb/indieauth-client-php#15]
The [current check for rel existence](https://github.com/indieweb/indieauth-client-php/blob/225ece31ddafaee3348eabdc915422c457498a84/src/IndieAuth/Client.php#L63):

```php
    if(isset($headers[$name][0]) && $headers[$name][0]) {
```

And [likewise for in-HTML](https://github.com/indieweb/indieauth-client-php/blob/225ece31ddafaee3348eabdc915422c457498a84/src/IndieAuth/Client.php#L73):

```php
    if(isset($data['rels'][$name][0]) && $data['rels'][$name][0]) {
```

Because of PHP’s wonderful typing, an empty string is `false`, so this check fails for `href=""`. But an empty `href` is perfectly valid and should make it to the next line for `\Mf2\resolveUrl` to resolve.

**Comment by aaronpk** [comment]
Did you really end up in a situation where your IndieAuth URL (home page) is also your Micropub endpoint? I'm working on a fix for this but it seems like it wouldn't actually happen.

**Comment by Zegnat** [comment]
I don’t remember the use-case I had back in August actually… I think I was testing with having my homepage also reply to IndieAuth requests, so no extra `auth` in the path (`https://example.com/` rather than `https://example.com/auth`), and it failing on IndieAuth endpoint discovery (not Micropub discovery).

**Comment by aaronpk** [comment]
Seems like a pretty unique use case, but this is still a bug. 😄  Fix incoming!
