### ISSUE TITLE
Support indieauth-metadata link rel and lookups

### ISSUE THREAD

**Issue by martymcguire** [indieweb/indieauth-client-php#18]
All those endpoints to learn about. And methods to support! And demoting `authorization_endpoint` and `token_endpoint` rel discovery to fallbacks if `indieauth-metadata` isn't found.

I won't list all the details here because they're in the spec, haha. :sweat_smile: 

- https://indieauth.spec.indieweb.org/#discovery-by-clients
- https://indieauth.spec.indieweb.org/#indieauth-server-metadata

**Comment by gRegorLove** [comment]
Closed by #19.
