### ISSUE TITLE
support identity URLs with non-trivial paths

### ISSUE THREAD

**Issue by karadaisy** [indieweb/indieauth-client-php#4]
For example for silo.pub &rarr; Twitter, I'd like to login with https://silo.pub/twitter.com/kylewmahan

I think it's just this line that needs to change:

https://github.com/indieweb/indieauth-client-php/blob/master/src/IndieAuth/Client.php#L17

**Comment by aaronpk** [comment]
Fixed in 6e0f628d81b6318e6ef7c1f75684d8869af0aae9
