### ISSUE TITLE
Please re-license or dual license to MIT

### ISSUE THREAD

**Issue by marclaporte** [indieweb/indieauth-client-php#9]
This is easier to do before there are many contributors.

IMO, the best would be if libs like this one eventually became bundled in FLOSS PHP apps and this is easier with the MIT license than the Apache license. I was part of a group that worked hard to change the Bootstrap license from Apache to MIT for easy inclusion in GPL/LGPL apps: https://github.com/twbs/bootstrap/issues/2054

In my case, it's to include in Tiki Wiki CMS Groupware, in the context of WikiSuite, for which IndieWeb is an inspiration.
https://tiki.org/ -> Tiki is the Free/Libre/Open Source Web Application with the most built-in features
https://tiki.org/License
http://wikisuite.org/ -> WikiSuite is the most comprehensive and integrated Free / Libre / Open Source software suite ever developed.
http://wikisuite.org/Component-criteria#IndieWeb

Thanks!

**Comment by marclaporte** [comment]
@aaronpk 
@cweiske 
@jonnybarnes

**Comment by cweiske** [comment]
I'm ok with the change from Apache to MIT.

**Comment by jonnybarnes** [comment]
If you need my permission then yes, I grant permission.

**Comment by marclaporte** [comment]
@aaronpk  ping :-)

**Comment by aaronpk** [comment]
Thanks everyone! I've made this available under both the Apache and MIT licenses.
